apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-operator-deployment.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "helm-operator-deployment.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "helm-operator-deployment.fullname" . }}
    spec:
      serviceAccountName: {{ include "helm-operator-deployment.fullname" . }}
      containers:
        - name: monitoring-operator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monitoring-operator"
