apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pushgateways.monitoring.elostech.cz
spec:
  group: monitoring.elostech.cz
  names:
    kind: Pushgateway
    listKind: PushgatewayList
    plural: pushgateways
    singular: pushgateway
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
      
