apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-operator-deployment.fullname" . }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.grafana: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"} }'
