apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: thanosreceives.monitoring.elostech.cz
spec:
  group: monitoring.elostech.cz
  names:
    kind: ThanosReceive
    listKind: ThanosReceiveList
    plural: thanosreceives
    singular: thanosreceive
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
