apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: thanos.monitoring.elostech.cz
spec:
  group: monitoring.elostech.cz
  names:
    kind: Thanos
    listKind: ThanosList
    plural: thanos
    singular: thanos
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
